### DISCUSSION TITLE
Thoughts about additional sensors

### DISCUSSION THREAD

**Discussion by GlennGoddard** [briis/hass-weatherflow2mqtt#83] [Ideas]
**EDIT** These two are Complete

I guess I never noticed that we don't get nomenclature for rain rate such as Light, Very Light, Moderate, Heavy (as seen in the WF App); this is different then the Precipitation Type.
[https://community.weatherflow.com/t/rain-intensity-values/806](url)

VERY LIGHT: < 0.25 mm/hour
LIGHT: ≥ 0.25, < 1.0 mm/hour
MODERATE: ≥ 1.0, < 4.0 mm/hour
HEAVY: ≥ 4.0, < 16.0 mm/hour
VERY HEAVY: ≥ 16.0, < 50 mm/hour
EXTREME: > 50.0 mm/hour

I've been looking into Absolute Humidity for humidity levels independent of temperature (I have been using DewPoint as this indicator but I think Absolute Humidity would handle this better)
Would need Vapor Pressure to calculate Absolute Humidity but does not need to be exposed (similar to how we have WBGT which requires black bulb temp which is calculated and not exposed to the user)

Thoughts on these two sensors?

**Comment by briis** [comment]
The first one, makes sense, and I can make that before the next release. That one will also require updates to the language files.
Absolute Humidity - Honestly, never heard about it. What would be the benefit of that sensor?

**Reply by GlennGoddard** [reply]
Absolute Humidity is the actual amount of water in volume of air.
Relative Humidity is the ratio of the amount of water in the air to the capacity of that air to hold water at the current temperature.
For the same amount of actual water in the air the relative humidity will go up when temperature goes down.
Absolute Humidity is a good indication of the actual humidity conditions independent of temperature.
Dewpoint can be used in a similar way as in the lower the dewpoint the higher the amount of water in air.

**Comment by briis** [comment]
OK, got it. I have no issues with adding that sensor to the system, if you can make the math/function.

The latest dev build, not includes the other Rain Intensity sensor. I made the text Capital Letters only, as in the App, but what is your view on that?

**Reply by GlennGoddard** [reply]
I can see arguments for both CAPITAL and lowercase.  I personally like Title Case, but I won't loose sleep over any of the choices.
I personally think ALL CAPS when it is not a message that requires attention draws attention away from items that deserve more attention.

**Reply by briis** [reply]
I buy your argument. I will make the text Title Case.

**Reply by GlennGoddard** [reply]
If you bought it, I should have put a higher price tag on it.

**Reply by briis** [reply]
Uploaded a new dev build, with text in Title Case

**Comment by GlennGoddard** [comment]
I'm working today, so it will be a few hours before I can update to the latest build.

**Comment by GlennGoddard** [comment]
I can see in my Home Assistance instance that Rain Intensity is Title Case but when I look in Helpers and Translations it is CAPITALIZED.
Am I missing something or did you update only the code that went into the Docker Dev build?
I looked to see if you used title() method.

**Reply by briis** [reply]
They are there now. I forgot to push to Github after the update

**Reply by GlennGoddard** [reply]
Good to know that I wasn't loosing my mind and I indeed could not find what was not there.
So yesterday I had 0.6 inch/hour (15 mm/hr) of rain at one point in time, but today no rain...at all.
This (rain intensity) should work but I'll let you know as soon as I can positively report.

I'll work on the Absolute Humidity part when I get the opportunity.  I've been occupied with getting weight from a load cell to HA via MQTT for my 3D printer filament.  The 'only' part I have left is pulling the MQTT message into HA and then the calculations for the length of filament based on the filament type (which I already pull in via a REST sensor).

**Reply by briis** [reply]
I am in to 3D printing also, so I will be happy to hear how that project goes

**Reply by GlennGoddard** [reply]
[https://community.home-assistant.io/t/prusa-mini-3d-printer-info/236240/42](https://community.home-assistant.io/t/prusa-mini-3d-printer-info/236240/42)

I have percent and weight in grams currently.  Percent seems kinda wasteful now, I didn't think about the fact that most spool reels are 1000g of filament.  I subtract the weight of the spool and holder so I am only measuring the actual filament.

**Comment by GlennGoddard** [comment]
Documenting for future reference:

In the temperature range of 5-50 C this a reasonable estimation for absolute humidity.
AH is Absolute Humidity
RH is Relative Humidity (range of 0.0 to 1.0, i.e. 25% RH is 0.25)
TK is Air Temperature in Kelvin

AH = (1320.65/TK)*RH*(10**((7.4475*(TK-273.14))/(TK-39.44))
partially coded for python already ** is exponent

Hopefully will be able to drop a (partial) PR in a few days.

**Comment by GlennGoddard** [comment]
Instead of converting g/m^3 to lb/ft^3, I decided to leave the units in metric and not convert to imperial.
This is exactly what is currently done for Solar Radiation where units are left metric vice imperial units.

**Comment by GlennGoddard** [comment]
I have the change ready with the exception of the usual that I leave for you to do.  Do you want me to submit PR now or wait until the long term stats is completed?  Of course, this will add one more thing to the long term stats.

I think it would be better to wait so I can update my branch to include all your most recent changes so their is less for you to merge and look at, but if you want it now, I can do it.  It is my Absolute_Humidity branch if you want to review it in all copious amounts of free time.

**Reply by briis** [reply]
Yes, just wait until I have the Long Term Stats completely figured out, then I will make that an official release, and we can start on the next. Thanks.

**Comment by GlennGoddard** [comment]
PR #86 added.
Needs @briis to fine tune (ie actually get it working) but other than not working, it is done.

Needs Absolute Humidity state_class and mqtt.

**Reply by briis** [reply]
Now added. Pushed to the dev build.

**Comment by GlennGoddard** [comment]
I have something weird going on with my logs but I get sensor data in HA including Absolute Humidity.

```
2021-10-12 16:57:09 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'dict object' has no attribute 'absolute_humidity' (value: {"dewpoint": {"max_day": 43.9, "max_day_time": "2021-10-12T22:58:00+00:00", "max_month": 54.7, "max_month_time": "2021-10-02T21:08:29+00:00", "max_all": 65.7, "max_all_time": "2021-08-15T01:27:22+00:00", "min_day": 36.0, "min_day_time": "2021-10-12T08:22:14+00:00", "min_month": 36.5, "min_month_time": "2021-10-11T13:30:37+00:00", "min_all": 36.5, "min_all_time": "2021-10-11T13:30:37+00:00"}, "relative_humidity": {"max_day": 96.66, "max_day_time": "2021-10-12T17:31:05+00:00", "max_month": 97.93, "max_month_time": "2021-10-01T16:37:00+00:00", "max_all": 100.0, "max_all_time": "2021-07-20T14:10:48+00:00", "min_day": 75.28, "min_day_time": "2021-10-12T23:45:00+00:00", "min_month": 54.78, "min_month_time": "2021-10-02T21:51:29+00:00", "min_all": 29.85, "min_all_time": "2021-08-13T23:39:51+00:00"}, "illuminance": {"max_day": 35512.0, "max_day_time": "2021-10-12T19:03:03+00:00", "max_month": 88501.0, "max_month_time": "2021-10-02T20:05:29+00:00", "max_all": 127533.0, "max_all_time": "2021-08-16T19:49:34+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "sealevel_pressure": {"max_day": 30.278, "max_day_time": "2021-10-12T07:00:01+00:00", "max_month": 30.349, "max_month_time": "2021-10-01T18:55:57+00:00", "max_all": 30.381, "max_all_time": "2021-09-20T18:11:54+00:00", "min_day": 30.026, "min_day_time": "2021-10-12T23:47:59+00:00", "min_month": 29.746, "min_month_time": "2021-10-05T14:32:16+00:00", "min_all": 29.543, "min_all_time": "2021-09-18T04:32:03+00:00"}, "rain_duration_today": {"max_day": 0.0, "max_day_time": "2021-10-12T07:00:01+00:00", "max_month": 257.0, "max_month_time": "2021-10-05T22:30:06+00:00", "max_all": 548.0, "max_all_time": "2021-09-19T06:23:32+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "rain_rate": {"max_day": 0.0, "max_day_time": "2021-10-12T07:00:01+00:00", "max_month": 2.28, "max_month_time": "2021-10-10T20:42:54+00:00", "max_all": 3.41, "max_all_time": "2021-09-27T20:58:41+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "solar_radiation": {"max_day": 296.0, "max_day_time": "2021-10-12T19:03:03+00:00", "max_month": 737.0, "max_month_time": "2021-10-02T20:05:30+00:00", "max_all": 1063.0, "max_all_time": "2021-08-16T19:49:34+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "lightning_strike_count_today": {"max_day": 0.0, "max_day_time": "2021-10-12T07:00:01+00:00", "max_month": 11.0, "max_month_time": "2021-10-10T22:36:52+00:00", "max_all": 25.0, "max_all_time": "2021-08-31T06:56:05+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "lightning_strike_energy": {"max_day": 16797055.0, "max_day_time": "2021-10-12T07:00:18+00:00", "max_month": 18874336.0, "max_month_time": "2021-10-02T06:39:45+00:00", "max_all": 18874336.0, "max_all_time": "2021-07-16T03:44:47+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "air_temperature": {"max_day": 49.1, "max_day_time": "2021-10-12T23:33:00+00:00", "max_month": 67.9, "max_month_time": "2021-10-02T22:48:27+00:00", "max_all": 93.4, "max_all_time": "2021-08-13T23:40:50+00:00", "min_day": 36.9, "min_day_time": "2021-10-12T08:10:15+00:00", "min_month": 37.4, "min_month_time": "2021-10-11T13:33:36+00:00", "min_all": 37.4, "min_all_time": "2021-10-11T13:33:36+00:00"}, "uv": {"max_day": 2.78, "max_day_time": "2021-10-12T19:03:04+00:00", "max_month": 6.42, "max_month_time": "2021-10-06T20:31:42+00:00", "max_all": 11.86, "max_all_time": "2021-08-16T19:49:34+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "wind_gust": {"max_day": 11.23, "max_day_time": "2021-10-12T22:00:01+00:00", "max_month": 34.78, "max_month_time": "2021-10-09T21:48:21+00:00", "max_all": 34.78, "max_all_time": "2021-10-09T21:48:21+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "wind_lull": {"max_day": 3.02, "max_day_time": "2021-10-12T11:52:23+00:00", "max_month": 3.62, "max_month_time": "2021-10-09T22:13:20+00:00", "max_all": 8.59, "max_all_time": "2021-09-25T22:34:35+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}, "wind_speed_avg": {"max_day": 5.12, "max_day_time": "2021-10-12T23:25:58+00:00", "max_month": 6.51, "max_month_time": "2021-10-09T21:48:21+00:00", "max_all": 13.58, "max_all_time": "2021-09-25T22:34:35+00:00", "min_day": 0.0, "min_day_time": null, "min_month": null, "min_month_time": null, "min_all": null, "min_all_time": null}}, template: {"attribution": "Powered by WeatherFlow2MQTT", "brand": "WeatherFlow", "max_day": "{{ value_json.absolute_humidity['max_day'] }}", "max_day_time": "{{ value_json.absolute_humidity['max_day_time'] }}", "max_month": "{{ value_json.absolute_humidity['max_month'] }}", "max_month_time": "{{ value_json.absolute_humidity['max_month_time'] }}", "max_all": "{{ value_json.absolute_humidity['max_all'] }}", "max_all_time": "{{ value_json.absolute_humidity['max_all_time'] }}", "min_day": "{{ value_json.absolute_humidity['min_day'] }}", "min_day_time": "{{ value_json.absolute_humidity['min_day_time'] }}", "min_month": "{{ value_json.absolute_humidity['min_month'] }}", "min_month_time": "{{ value_json.absolute_humidity['min_month_time'] }}", "min_all": "{{ value_json.absolute_humidity['min_all'] }}", "min_all_time": "{{ value_json.absolute_humidity['min_all_time'] }}"})
```

Too early to see any LTS for now.  I see Absolute Humidity as an option but no data yet (expected since only been running an hour or so at this point in time).

I didn't think about it until I saw the standard eye icon but maybe mdi:water or mdi:water-opacity would be good choices.

**Reply by GlennGoddard** [reply]
ah...must be an indention issue somewhere.  14 sensors are 'Attributes' to Absolute Humidity in HA; possibly all the sensors that have stored Hi/Lows stored locally in this program.  Under each of the 14 sensors that are under Absolute Humidity are 12 min/max attributes.

**Reply by briis** [reply]
I am not sure I understand your issue(s)?
I got the Absolute Humidity right away with values, and it has been stable ever since.

Is there another issue here also?

**Reply by GlennGoddard** [reply]
I too am getting the data for Absolute Humidity and now that I have a few hours of data the LTS is verified working for it.
But....
Look at sensor.wf_absolute_humidity under dev tools states to see what I mean.
```
state_class: measurement
dewpoint:
  max_day: 42.4
  max_day_time: '2021-10-13T07:01:51+00:00'
  max_month: 54.7
  max_month_time: '2021-10-02T21:08:29+00:00'
  max_all: 65.7
  max_all_time: '2021-08-15T01:27:22+00:00'
  min_day: 38.8
  min_day_time: '2021-10-13T14:13:43+00:00'
  min_month: 36
  min_month_time: '2021-10-12T08:22:14+00:00'
  min_all: 36
  min_all_time: '2021-10-12T08:22:14+00:00'
relative_humidity:
  max_day: 96.77
  max_day_time: '2021-10-13T09:38:49+00:00'
  max_month: 97.93
  max_month_time: '2021-10-01T16:37:00+00:00'
  max_all: 100
  max_all_time: '2021-07-20T14:10:48+00:00'
  min_day: 95.55
  min_day_time: '2021-10-13T07:00:51+00:00'
  min_month: 54.78
  min_month_time: '2021-10-02T21:51:29+00:00'
  min_all: 29.85
  min_all_time: '2021-08-13T23:39:51+00:00'
illuminance:
  max_day: 73
  max_day_time: '2021-10-13T14:18:42+00:00'
  max_month: 88501
  max_month_time: '2021-10-02T20:05:29+00:00'
  max_all: 127533
  max_all_time: '2021-08-16T19:49:34+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
sealevel_pressure:
  max_day: 30.057
  max_day_time: '2021-10-13T14:16:44+00:00'
  max_month: 30.349
  max_month_time: '2021-10-01T18:55:57+00:00'
  max_all: 30.381
  max_all_time: '2021-09-20T18:11:54+00:00'
  min_day: 29.976
  min_day_time: '2021-10-13T07:10:50+00:00'
  min_month: 29.746
  min_month_time: '2021-10-05T14:32:16+00:00'
  min_all: 29.543
  min_all_time: '2021-09-18T04:32:03+00:00'
rain_duration_today:
  max_day: 0
  max_day_time: '2021-10-13T07:00:03+00:00'
  max_month: 257
  max_month_time: '2021-10-05T22:30:06+00:00'
  max_all: 548
  max_all_time: '2021-09-19T06:23:32+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
rain_rate:
  max_day: 0
  max_day_time: '2021-10-13T07:00:03+00:00'
  max_month: 2.28
  max_month_time: '2021-10-10T20:42:54+00:00'
  max_all: 3.41
  max_all_time: '2021-09-27T20:58:41+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
solar_radiation:
  max_day: 1
  max_day_time: '2021-10-13T14:17:43+00:00'
  max_month: 737
  max_month_time: '2021-10-02T20:05:30+00:00'
  max_all: 1063
  max_all_time: '2021-08-16T19:49:34+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
lightning_strike_count_today:
  max_day: 0
  max_day_time: '2021-10-13T07:00:03+00:00'
  max_month: 11
  max_month_time: '2021-10-10T22:36:52+00:00'
  max_all: 25
  max_all_time: '2021-08-31T06:56:05+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
lightning_strike_energy:
  max_day: 16797055
  max_day_time: '2021-10-13T07:00:51+00:00'
  max_month: 18874336
  max_month_time: '2021-10-02T06:39:45+00:00'
  max_all: 18874336
  max_all_time: '2021-07-16T03:44:47+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
air_temperature:
  max_day: 43.5
  max_day_time: '2021-10-13T07:00:51+00:00'
  max_month: 67.9
  max_month_time: '2021-10-02T22:48:27+00:00'
  max_all: 93.4
  max_all_time: '2021-08-13T23:40:50+00:00'
  min_day: 39.8
  min_day_time: '2021-10-13T14:07:44+00:00'
  min_month: 36.9
  min_month_time: '2021-10-12T08:10:15+00:00'
  min_all: 36.9
  min_all_time: '2021-10-12T08:10:15+00:00'
uv:
  max_day: 0
  max_day_time: '2021-10-13T07:00:03+00:00'
  max_month: 6.42
  max_month_time: '2021-10-06T20:31:42+00:00'
  max_all: 11.86
  max_all_time: '2021-08-16T19:49:34+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
wind_gust:
  max_day: 38.7
  max_day_time: '2021-10-13T07:02:50+00:00'
  max_month: 51.4
  max_month_time: '2021-10-13T06:55:50+00:00'
  max_all: 51.4
  max_all_time: '2021-10-13T06:55:50+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
wind_lull:
  max_day: 10.33
  max_day_time: '2021-10-13T07:01:50+00:00'
  max_month: 16.67
  max_month_time: '2021-10-13T06:58:51+00:00'
  max_all: 16.67
  max_all_time: '2021-10-13T06:58:51+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
wind_speed_avg:
  max_day: 26.73
  max_day_time: '2021-10-13T07:01:50+00:00'
  max_month: 23.82
  max_month_time: '2021-10-13T06:58:51+00:00'
  max_all: 23.82
  max_all_time: '2021-10-13T06:58:51+00:00'
  min_day: 0
  min_day_time: null
  min_month: null
  min_month_time: null
  min_all: null
  min_all_time: null
unit_of_measurement: g/m^3
friendly_name: WF Absolute Humidity
```
![dev](https://user-images.githubusercontent.com/61597338/137153365-65c3fbe4-fda8-4278-8ee5-ae9b6affaeb8.jpg)
