### ISSUE TITLE
Template Entity Error - Daily Forecast

### ISSUE THREAD

**Issue by twinkie0101** [briis/hass-weatherflow2mqtt#166]
### Home Assistant Version?

 	core-2022.7.4

### Add-On or Self Hosted?

HA Supervised (Add-On)

### Weatherflow2MQTT version?

3.1.1 

### What happened?

I keep getting the error below for my weather template.  Maybe this is due to me trying to create two templates (one for hourly and one for daily)?  The yaml for each template is below:

```
#Weatherflow
weather:
  - platform: template
    name: My Local Weather
    condition_template: "{{ states('sensor.hub_hb_TEMPEST-ID_weather') }}"
    temperature_template: "{{ states('sensor.tempest_st_TEMPEST-ID_temperature') | float}}"
    humidity_template: "{{ states('sensor.tempest_st_TEMPEST-ID_humidity')| int }}"
    pressure_template: "{{ states('sensor.tempest_st_TEMPEST-ID_sea_level_pressure')| float }}"
    wind_speed_template: "{{ states('sensor.tempest_st_TEMPEST-ID_wind_speed_avg') }}"
    wind_bearing_template: "{{ states('sensor.tempest_st_TEMPEST-ID_wind_bearing_avg')| int }}"
    visibility_template: "{{ states('sensor.tempest_st_TEMPEST-ID_visibility')| float }}"
    forecast_template: "{{ state_attr('sensor.hub_hb_TEMPEST-ID_weather', 'hourly_forecast') }}"
    
  - platform: template
    name: My Daily Local Weather
    condition_template: "{{ states('sensor.hub_hb_TEMPEST-ID_weather') }}"
    temperature_template: "{{ states('sensor.tempest_st_TEMPEST-ID_temperature') | float}}"
    humidity_template: "{{ states('sensor.tempest_st_TEMPEST-ID_humidity')| int }}"
    pressure_template: "{{ states('sensor.tempest_st_TEMPEST-ID_sea_level_pressure')| float }}"
    wind_speed_template: "{{ states('sensor.tempest_st_TEMPEST-ID_wind_speed_avg') }}"
    wind_bearing_template: "{{ states('sensor.tempest_st_TEMPEST-ID_wind_bearing_avg')| int }}"
    visibility_template: "{{ states('sensor.tempest_st_TEMPEST-ID_visibility')| float }}"
    forecast_template: "{{ state_attr('sensor.hub_hb_TEMPEST-ID_weather', 'daily_forecast') }}"

```

### Relevant log output

```shell
Logger: homeassistant.helpers.template_entity
Source: helpers/template_entity.py:108
First occurred: 9:02:54 AM (10 occurrences)
Last logged: 9:02:54 AM

TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.tempest_st_00057917_temperature') | float}}' but no default was specified') while processing template 'Template("{{ states('sensor.tempest_st_00057917_temperature') | float}}")' for attribute '_temperature' in entity 'weather.my_daily_local_weather'
TemplateError('ValueError: Template error: int got invalid input 'unknown' when rendering template '{{ states('sensor.tempest_st_00057917_humidity')| int }}' but no default was specified') while processing template 'Template("{{ states('sensor.tempest_st_00057917_humidity')| int }}")' for attribute '_humidity' in entity 'weather.my_daily_local_weather'
TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.tempest_st_00057917_sea_level_pressure')| float }}' but no default was specified') while processing template 'Template("{{ states('sensor.tempest_st_00057917_sea_level_pressure')| float }}")' for attribute '_pressure' in entity 'weather.my_daily_local_weather'
TemplateError('ValueError: Template error: int got invalid input 'unknown' when rendering template '{{ states('sensor.tempest_st_00057917_wind_bearing_avg')| int }}' but no default was specified') while processing template 'Template("{{ states('sensor.tempest_st_00057917_wind_bearing_avg')| int }}")' for attribute '_wind_bearing' in entity 'weather.my_daily_local_weather'
TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.tempest_st_00057917_visibility')| float }}' but no default was specified') while processing template 'Template("{{ states('sensor.tempest_st_00057917_visibility')| float }}")' for attribute '_visibility' in entity 'weather.my_daily_local_weather'
```
```
