### ISSUE TITLE
container error: NameError: name 'false' is not defined

### ISSUE THREAD

**Issue by olonsoft** [briis/hass-weatherflow2mqtt#65]
Hello
I 've tried to run the container on a raspberry pi and created the following docker-compose file:

```yaml
version: "3.8"
services:
  wf2mqtt:
    image: briis/weatherflow2mqtt:latest
    container_name: wf2mqtt
    environment:
      - TZ=Europe/Athens
      - TEMPEST_DEVICE=false 
      - UNIT_SYSTEM=metric 
      - LANGUAGE=en 
      - RAPID_WIND_INTERVAL=0 
      - DEBUG=False 
      - ELEVATION=0
      - WF_HOST=0.0.0.0
      - WF_PORT=50222
      - MQTT_HOST=192.168.1.10
      - MQTT_PORT=1883
      - MQTT_USERNAME=user
      - MQTT_PASSWORD=pass
      - MQTT_DEBUG=False 
      - ADD_FORECAST=False
      - STATION_ID= 
      - STATION_TOKEN= 
      - FORECAST_INTERVAL=30
    volumes:
      - ./config:/usr/local/config      
    ports:
      - 0.0.0.0:50222:50222/udp
    restart: unless-stopped
```

this is the log output:

```log
Creating wf2mqtt ... done
Attaching to wf2mqtt
wf2mqtt    | DEBUG:asyncio:Using selector: EpollSelector
wf2mqtt    | INFO:weatherflow2mqtt.weatherflow_mqtt:Timezone is Europe/Athens
wf2mqtt    | Traceback (most recent call last):
wf2mqtt    |   File "/usr/local/bin/weatherflow2mqtt", line 33, in <module>
wf2mqtt    |     sys.exit(load_entry_point('weatherflow2mqtt==0.10.0', 'console_scripts', 'weatherflow2mqtt')())
wf2mqtt    |   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-0.10.0-py3.9.egg/weatherflow2mqtt/__main__.py", line 10, in main
wf2mqtt    |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
wf2mqtt    |     return loop.run_until_complete(main)
wf2mqtt    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
wf2mqtt    |     return future.result()
wf2mqtt    |   File "/usr/local/lib/python3.9/site-packages/weatherflow2mqtt-0.10.0-py3.9.egg/weatherflow2mqtt/weatherflow_mqtt.py", line 60, in main
wf2mqtt    |   File "<string>", line 1, in <module>
wf2mqtt    | NameError: name 'false' is not defined
```
